inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'lib/definerails_sensitivedata/models/sensitive_data_object__mongoid.rb'
  NewCops: enable

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - 'rakelib/rakefile.rake'
